AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the AWS::M2::Application resource type

Globals:
  Function:
    Timeout: 180  # docker start-up times can be long for SAM CLI
    MemorySize: 1024

Resources:
  TypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: software.amazon.m2.application.HandlerWrapper::handleRequest
      Runtime: java11
      CodeUri: ./target/aws-m2-application-1.0.jar

  TestEntrypoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: software.amazon.m2.application.HandlerWrapper::testEntrypoint
      Runtime: java11
      CodeUri: ./target/aws-m2-application-1.0.jar

